const DB={orders:"al_tayeb_orders",jobs:"al_tayeb_jobs",employees:"al_tayeb_employees",finance:"al_tayeb_finance",inventory:"al_tayeb_inventory",customers:"al_tayeb_customers",contracts:"al_tayeb_contracts",vehicles:"al_tayeb_vehicles",operations:"al_tayeb_operations",leads:"al_tayeb_leads",quotes:"al_tayeb_quotes",invoices:"al_tayeb_invoices",attendance:"al_tayeb_attendance",payroll:"al_tayeb_payroll",suppliers:"al_tayeb_suppliers",calendar:"al_tayeb_calendar",files:"al_tayeb_files",audit:"al_tayeb_audit",site:"al_tayeb_site"};
const $=s=>document.querySelector(s),get=k=>{try{return JSON.parse(localStorage.getItem(k)||"[]")}catch{return[]}},put=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),today=()=>new Date().toISOString().slice(0,10),money=n=>new Intl.NumberFormat("ar-SD").format(Number(n)||0)+" SDG",esc=v=>String(v??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
let page="dashboard";
const P={dashboard:["الرئيسية",null],orders:["طلبات الخدمات",[["service","الخدمة"],["name","العميل"],["phone","الجوال"],["city","المنطقة"],["date","التاريخ"],["status","الحالة"]]],operations:["التنفيذ والمهام",[["title","المهمة"],["order","الطلب"],["employee","المسؤول"],["date","التاريخ"],["status","الحالة"]]],customers:["العملاء",[["name","العميل"],["phone","الجوال"],["city","المنطقة"],["type","النوع"],["notes","ملاحظات"]]],leads:["العملاء المحتملون",[["name","الاسم/الشركة"],["phone","الجوال"],["source","المصدر"],["service","الخدمة"],["status","الحالة"]]],quotes:["عروض الأسعار",[["number","رقم العرض"],["customer","العميل"],["service","الخدمة"],["total","القيمة"],["status","الحالة"]]],invoices:["الفواتير",[["number","الفاتورة"],["customer","العميل"],["date","التاريخ"],["total","الإجمالي"],["paid","المدفوع"],["status","الحالة"]]],employees:["الموظفون",[["name","الاسم"],["role","الوظيفة"],["phone","الجوال"],["salary","الراتب"],["start","البداية"],["status","الحالة"]]],attendance:["الحضور والانصراف",[["date","التاريخ"],["employee","الموظف"],["in","الحضور"],["out","الانصراف"],["status","الحالة"]]],payroll:["الرواتب",[["month","الشهر"],["employee","الموظف"],["salary","الراتب"],["bonus","إضافي"],["deduction","خصم"],["status","الحالة"]]],jobs:["طلبات التوظيف",[["name","الاسم"],["phone","الجوال"],["job","الوظيفة"],["city","المنطقة"],["exp","الخبرة"],["status","الحالة"]]],finance:["المالية والمصروفات",[["date","التاريخ"],["type","النوع"],["note","البيان"],["amount","المبلغ"],["category","التصنيف"]]],inventory:["المخزون والمعدات",[["name","الصنف"],["category","التصنيف"],["qty","الكمية"],["min","الحد الأدنى"],["cost","التكلفة"],["status","الحالة"]]],suppliers:["الموردون",[["name","المورد"],["phone","الجوال"],["category","التوريد"],["balance","الرصيد"]]],vehicles:["المركبات",[["name","المركبة"],["plate","اللوحة"],["driver","السائق"],["status","الحالة"]]],contracts:["العقود",[["number","رقم العقد"],["name","العميل"],["start","البداية"],["end","النهاية"],["value","القيمة"],["status","الحالة"]]],calendar:["التقويم والمواعيد",[["date","التاريخ"],["time","الوقت"],["title","العنوان"],["employee","المسؤول"],["status","الحالة"]]],files:["ملفات الشركة",null],website:["إدارة الموقع",[["whatsapp","واتساب"],["city","المدينة"],["hours","ساعات العمل"],["notice","تنبيه"]]],reports:["التقارير",null],audit:["سجل النشاط",null],settings:["الإعدادات والنسخ الاحتياطي",null]};
function log(a){let x=get(DB.audit);x.unshift({date:new Date().toISOString(),action:a});put(DB.audit,x.slice(0,500))}
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2000)}
function init(){let n=$("#nav");n.innerHTML=Object.keys(P).map(k=>"<button data-page='"+k+"'>"+P[k][0]+"</button>").join("");n.querySelectorAll("button").forEach(b=>b.onclick=()=>{page=b.dataset.page;render();$("#side").classList.remove("open")});$("#toggle").onclick=()=>$("#side").classList.toggle("open");$("#demo").onclick=demo;$("#backup").onclick=backup;render()}
function render(){document.querySelectorAll("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===page));$("#title").textContent=P[page][0];if(page==="dashboard")dashboard();else if(page==="files")files();else if(page==="reports")reports();else if(page==="audit")audit();else if(page==="settings")settings();else tablePage()}
function dashboard(){let f=get(DB.finance),inc=f.filter(x=>x.type==="income").reduce((s,x)=>s+Number(x.amount),0),exp=f.filter(x=>x.type==="expense").reduce((s,x)=>s+Number(x.amount),0),inv=get(DB.invoices),due=inv.reduce((s,x)=>s+Math.max(0,Number(x.total)-Number(x.paid||0)),0);$("#app").innerHTML="<div class='wrap'><div class='notice'>هذه نسخة تشغيلية محلية. استخدم «بيانات تجريبية» للتجربة. الربط بين عدة أجهزة يحتاج Backend وقاعدة بيانات وحسابات دخول.</div><div class='cards'><div class='card'><span>طلبات الخدمات</span><div class='metric'>"+get(DB.orders).length+"</div></div><div class='card'><span>العملاء</span><div class='metric'>"+get(DB.customers).length+"</div></div><div class='card'><span>الموظفون</span><div class='metric'>"+get(DB.employees).length+"</div></div><div class='card'><span>صافي المالية</span><div class='metric'>"+money(inc-exp)+"</div></div><div class='card'><span>المستحقات</span><div class='metric'>"+money(due)+"</div></div></div><div class='grid2'><div class='panel'><h2>آخر الطلبات</h2>"+tableHTML(get(DB.orders).slice(-8).reverse(),P.orders[1])+"</div><div class='panel'><h2>الملخص المالي</h2><p>الإيرادات: <b>"+money(inc)+"</b></p><p>المصروفات: <b>"+money(exp)+"</b></p><p>الصافي: <b>"+money(inc-exp)+"</b></p><p>المستحقات: <b>"+money(due)+"</b></p></div></div></div>"}
function tablePage(){let fs=P[page][1],k=DB[page],a=get(k);$("#app").innerHTML="<div class='wrap'><div class='section-title'><h2>"+P[page][0]+"</h2><div><button class='primary' id='add'>إضافة جديد</button><button class='secondary' id='csv'>CSV</button></div></div><div class='panel'>"+tableHTML(a,fs)+"</div></div>";$("#add").onclick=()=>addForm();$("#csv").onclick=()=>csv(k);document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>removeRow(k,+b.dataset.del))}
function tableHTML(a,fs){if(!a.length)return "<div class='empty'>لا توجد سجلات بعد.</div>";return "<div class='tablewrap'><table class='table'><tr>"+fs.map(f=>"<th>"+f[1]+"</th>").join("")+"<th>إجراء</th></tr>"+a.map((x,i)=>"<tr>"+fs.map(f=>"<td>"+esc(f[0]==="amount"||f[0]==="total"||f[0]==="salary"||f[0]==="value"?money(x[f[0]]):x[f[0]])+"</td>").join("")+"<td><button class='danger' data-del='"+i+"'>حذف</button></td></tr>").join("")+"</table></div>"}
function addForm(){let fs=P[page][1],html="<h2>"+P[page][0]+"</h2><form class='form' id='form'>"+fs.map(f=>"<label>"+f[1]+"<input name='"+f[0]+"' "+((f[0]==="date"||f[0]==="start"||f[0]==="end")?"type='date'":"")+" required></label>").join("")+"<button class='primary full'>حفظ</button></form>";showModal(html);$("#form").onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));d.id="REC-"+Date.now();d.createdAt=new Date().toISOString();let k=DB[page],a=get(k);a.push(d);put(k,a);log("إضافة: "+P[page][0]);closeModal();render();toast("تم الحفظ")}}
function removeRow(k,i){if(confirm("هل تريد حذف السجل؟")){let a=get(k);a.splice(i,1);put(k,a);log("حذف سجل");render()}}
function showModal(h){$("#modal").innerHTML="<div class='dialog'><button class='close' onclick='closeModal()'>×</button>"+h+"</div>";$("#modal").classList.add("show")}function closeModal(){$("#modal").classList.remove("show")}
function files(){let a=get(DB.files);$("#app").innerHTML="<div class='wrap'><div class='section-title'><h2>ملفات الشركة</h2><input id='fi' type='file' multiple></div><div class='notice'>حالياً يتم حفظ معلومات الملفات محلياً فقط.</div><div class='panel'>"+(a.length?a.map((x,i)=>"<div class='item'><span><b>"+esc(x.name)+"</b><br><small>"+esc(x.type)+" — "+x.size+" bytes</small></span><button class='danger' data-file='"+i+"'>حذف</button></div>").join(""):"<div class='empty'>لا توجد ملفات.</div>")+"</div></div>";$("#fi").onchange=e=>{let a=get(DB.files);[...e.target.files].forEach(f=>a.push({name:f.name,type:f.type,size:f.size,added:new Date().toISOString()}));put(DB.files,a);render()};document.querySelectorAll("[data-file]").forEach(b=>b.onclick=()=>removeRow(DB.files,+b.dataset.file))}
function reports(){let f=get(DB.finance),inc=f.filter(x=>x.type==="income").reduce((s,x)=>s+Number(x.amount),0),exp=f.filter(x=>x.type==="expense").reduce((s,x)=>s+Number(x.amount),0);$("#app").innerHTML="<div class='wrap'><div class='grid3'><div class='panel'><h2>التشغيل</h2><p>الطلبات: <b>"+get(DB.orders).length+"</b></p><p>المهام: <b>"+get(DB.operations).length+"</b></p></div><div class='panel'><h2>المالية</h2><p>الإيرادات: <b>"+money(inc)+"</b></p><p>المصروفات: <b>"+money(exp)+"</b></p><p>الصافي: <b>"+money(inc-exp)+"</b></p></div><div class='panel'><h2>النسخ</h2><button class='primary' onclick='backup()'>تنزيل JSON</button><button class='secondary' onclick='window.print()'>طباعة</button></div></div></div>"}
function audit(){let a=get(DB.audit);$("#app").innerHTML="<div class='wrap'><div class='panel'><h2>سجل النشاط</h2>"+(a.length?a.map(x=>"<div class='item'><span>"+esc(x.action)+"</span><small>"+esc(x.date)+"</small></div>").join(""):"<div class='empty'>لا يوجد نشاط.</div>")+"</div></div>"}
function settings(){$("#app").innerHTML="<div class='wrap'><div class='grid2'><div class='panel'><h2>النسخ الاحتياطي</h2><button class='primary' onclick='backup()'>تصدير كل البيانات</button><br><br><label class='secondary upload'>استعادة JSON<input id='restore' type='file' accept='.json' hidden></label></div><div class='panel'><h2>الأمان</h2><p>هذه النسخة لا تحتوي على تسجيل دخول أو قاعدة بيانات مشتركة.</p><button class='danger' onclick='clearAll()'>مسح بيانات الجهاز</button></div></div></div>";$("#restore").onchange=e=>restore(e.target.files[0])}
function backup(){let d={version:1,exportedAt:new Date().toISOString()};Object.entries(DB).forEach(([n,k])=>d[n]=get(k));let b=new Blob([JSON.stringify(d,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="al-tayeb-backup-"+today()+".json";a.click();URL.revokeObjectURL(a.href)}
function restore(file){if(!file)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);Object.entries(DB).forEach(([n,k])=>{if(Array.isArray(d[n]))put(k,d[n])});render();toast("تمت الاستعادة")}catch{alert("ملف غير صالح")}};r.readAsText(file)}
function csv(k){let a=get(k);if(!a.length)return toast("لا توجد بيانات");let s=JSON.stringify(a,null,2),b=new Blob([s],{type:"application/json"}),u=URL.createObjectURL(b),a1=document.createElement("a");a1.href=u;a1.download=page+"-export.json";a1.click();URL.revokeObjectURL(u)}
function clearAll(){if(confirm("مسح جميع بيانات لوحة الإدارة من هذا الجهاز؟")){Object.values(DB).forEach(k=>localStorage.removeItem(k));render();toast("تم المسح")}}
function demo(){let d={orders:[{id:"ORD-DEMO-001",service:"تنظيف عميق",name:"عميل تجريبي",city:"الخرطوم",date:today(),status:"جديد"}],customers:[{id:"CUS-DEMO-001",name:"شركة تجريبية",phone:"000000000",city:"الخرطوم",type:"شركة"}],employees:[{id:"EMP-DEMO-001",name:"موظف تجريبي",role:"مشرف ميداني",salary:"600000",status:"نشط"}],finance:[{id:"FIN-DEMO-001",type:"income",amount:"1500000",date:today(),note:"إيراد تجريبي"}],inventory:[{id:"STK-DEMO-001",name:"معدات تنظيف",qty:"5",status:"جيد"}],operations:[{id:"TASK-DEMO-001",title:"تنفيذ تنظيف تجريبي",order:"ORD-DEMO-001",employee:"موظف تجريبي",date:today(),status:"مجدولة"}]};Object.entries(d).forEach(([n,v])=>put(DB[n],get(DB[n]).concat(v)));log("تحميل بيانات تجريبية");render();toast("تم تحميل البيانات التجريبية")}
init();